### ISSUE TITLE
Setup on windows

### ISSUE THREAD

**Issue by elitallman** [Emsu/prophet#11]
Anyone here successfully set this project up on Windows? I have tried Anaconda 2.1/2.7.9 64 bit python, and CPython 2.7.9 32 bit... get ambiguous errors about Visual C++ or missing dependencies.

Log from Anaconda 2.1/64 bit python: http://pastebin.com/Yx9i1zKP

**Comment by Emsu** [comment]
Hey Eli,

I'm going to close this for now since you got this to work. Looks like you reopened it when you commented.
