### ISSUE TITLE
Misleading error message 

### ISSUE THREAD

**Issue by z123** [Emsu/prophet#12]
https://github.com/Emsu/prophet/blob/master/prophet/app.py#L171. Currently the name property has to be set as 'prices' not 'price'. Not sure what you intended the price data to be labeled as.

**Comment by Emsu** [comment]
Thanks for catching that @z123. I meant for it to be 'prices'. I've updated it to reflect that in this [commit](https://github.com/Emsu/prophet/commit/140ac2092172f553f694082842215eb64e43cfa1).
