### ISSUE TITLE
[Proposal] Plotting of daily returns and orders

### ISSUE THREAD

**Issue by mpritham** [Emsu/prophet#20]
It would be nice if there were a way to plot some key metrics from the backtests such as how the daily returns changed overtime or what orders were filled and when. Currently, I can manually insert plotting statements on the backtest daily returns time series.

**Comment by Emsu** [comment]
@mpritham This should be possible with by adding hooks to the backtest function. I haven't had time to work on prophet in awhile due to work but I'll try to take a look why my schedule is free.

**Comment by simongarisch** [comment]
This can be closed if you are happy with the changes in my pull request. Can modify if you have suggestions.
